#!groovy

pipeline {
    agent {
        node {
            label 'ssl_daintvm1'
        }
    }
    environment {
        SPACK_ROOT = '/apps/daint/SSL/HPX/spack'
    }
    stages {
        stage('build_test') {
            matrix {
                axes {
                    axis {
                        name 'configuration_name'
                        values 'gcc-newest', 'gcc-oldest'
                    }
                }
                stages {
                    stage('checkout') {
                        steps {
                            dir('hpx') {
                                checkout scm
                                echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
                            }
                        }
                    }
                    stage('build') {
                            steps {
                                dir('hpx') {
                                    sh '''
                                    #!/bin/bash -l
                                    set -eu
                                    echo ${ghprbActualCommit}
                                    echo ${ghprbActualCommitAuthor}
                                    echo ${ghprbActualCommitEmail}
                                    echo ${ghprbPullDescription}
                                    echo ${ghprbPullId}
                                    echo ${ghprbPullLink}
                                    echo ${ghprbPullTitle}
                                    echo ${ghprbSourceBranch}
                                    echo ${ghprbTargetBranch}
                                    echo ${ghprbCommentBody}
                                    echo ${sha1}
                                    source tools/jenkins/env-${configuration_name}.sh
                                    sbatch --wait tools/jenkins/batch-${configuration_daint_constraint}.sh
                                    '''
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/jenkins-hpx-log.*', fingerprint: true
        }
    }
}

